Fix broken 'build all templates' workflow (#4834)
* Added '' around if value'

* allow jobs to continue if one fails

* add install step

* use default options for pnpm action install

* fail the action if any builds fail but only at the end

* move install step around

* try fix pnpm install issue

* have action run in a fresh directory

* try install pnpm from diff directory

* remove working-directory option from pnpm install

* install hugo when using the hugo starter

* remove checkout step

* set failed variable

* fix variable passing

* fix issue with github issues not being created due to typo

* Update .github/workflows/build-starter-templates.yml

Co-authored-by: Matt Wicks [SSW] <wicksipedia@users.noreply.github.com>

* use latest flag for pnpm install

---------

Co-authored-by: Matt Wicks [SSW] <wicksipedia@users.noreply.github.com>

diff --git a/.github/workflows/build-starter-templates.yml b/.github/workflows/build-starter-templates.yml
--- a/.github/workflows/build-starter-templates.yml
+++ b/.github/workflows/build-starter-templates.yml
@@ -6,8 +6,9 @@ on:
     - cron: '0 9 * * 1-5'
 
 jobs:
-  test:
+  build-templates:
     runs-on: ubuntu-latest
+    continue-on-error: true
     strategy:
       matrix:
         package-manager: [yarn, npm, pnpm]
@@ -19,11 +20,10 @@ jobs:
           - tinasaurus
           - basic
         node-version: [18, 20, 22]
+    outputs:
+      failed: ${{ steps.report-errors.outputs.failed }}
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
@@ -31,27 +31,34 @@ jobs:
 
       - uses: pnpm/action-setup@v4
         name: Install pnpm
-        if: ${{ matrix.package-manager == pnpm }}
-        id: pnpm-install
         with:
-          package_json_file: package.json
-          run_install: false
+          version: latest
+        if: ${{ matrix.package-manager == 'pnpm' }}
+
+      - name: Setup Hugo
+        uses: peaceiris/actions-hugo@v3
+        with:
+          hugo-version: 'latest'
+        if: ${{ matrix.template == 'tina-hugo-starter' }}
 
       - name: Run create-tina-app
-        run: |
-          npx create-tina-app@latest template-repo --pkg-manager ${{ matrix.package-manager }} --template ${{ matrix.template }}
-        working-directory: ./
+        run: npx create-tina-app@latest template-repo --pkg-manager ${{ matrix.package-manager }} --template ${{ matrix.template }}
 
       - name: Run build
         run: |
           cd template-repo
-          ${{ matrix.package-manager }} run build
+          ${{ matrix.package-manager }} install && ${{ matrix.package-manager }} run build-local
 
       - name: Report errors
+        continue-on-error: false
+        id: report-errors
         if: failure()
         run: |
           ISSUE_TITLE="Starter template '${{ matrix.template }}' failed to build with ${{ matrix.package-manager }}"
           RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+
+          echo $ISSUE_TITLE >> $GITHUB_STEP_SUMMARY
+          echo "failed=true" >> "$GITHUB_OUTPUT"
 
           echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
           if gh issue list --state open --limit 100 --search "$ISSUE_TITLE" | grep -q "$ISSUE_TITLE"; then
@@ -60,5 +67,19 @@ jobs:
             echo "Creating a new issue..."
             gh issue create --title "$ISSUE_TITLE" \
               --body "The **${{ matrix.template }}** starter template failed to build using **${{ matrix.package-manager }}**.\n\nCheck the full workflow logs for more details: [View Workflow Run]($RUN_URL)" \
-              --labels "bug"
+              --label "bug"
+          fi
+
+  # Required to check for failures due to the `continue-on-error` being set to true.
+  check-failures:
+    needs: build-templates
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if any job failed
+        run: |
+          if [[ "${{ needs.build-templates.outputs.failed }}" == "true" ]]; then
+            echo "One or more commands failed."
+            exit 1
+          else
+            echo "All commands succeeded."
           fi
